version: '3'

services:

  http:
    container_name: microservice_account_http
    image: nginx:latest
    restart: always
    ports:
      - "8088:80"
      - "433:443"
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/dev/microservice_account_http/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/dev/microservice_account_http/nginx/log:/var/log/nginx
    networks:
      - microservice_account_network

  php:
    container_name: microservice_account_php
    image: marcelofabianov/php-8.1-fpm-pgsql
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9043:9000"
    networks:
      - microservice_account_network

  db:
    container_name: microservice_account_db
    image: postgres:13
    environment:
      PGPASSWORD: '${DB_PASSWORD:-password}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'microservice_account_db:/var/lib/postgresql/data'
    ports:
      - "5421:5432"
    networks:
      - microservice_account_network

  db_testing:
    container_name: microservice_account_db_testing
    image: postgres:13
    environment:
      PGPASSWORD: '${TEST_DB_PASSWORD:-password}'
      POSTGRES_DB: '${TEST_DB_DATABASE}'
      POSTGRES_USER: '${TEST_DB_USERNAME}'
      POSTGRES_PASSWORD: '${TEST_DB_PASSWORD:-password}'
    volumes:
      - 'microservice_account_db_testing:/var/lib/postgresql/data'
    ports:
      - "5411:5432"
    networks:
      - microservice_account_network

  cache:
    container_name: microservice_account_cache
    image: redis:latest
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./.docker/dev/microservice_account_cache/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - 'microservice_account_cache:/data'
    ports:
      - "6387:6379"
    networks:
      - microservice_account_network

networks:
  microservice_account_network:
    driver: bridge

volumes:
  microservice_account_cache:
    driver: local
  microservice_account_db:
    driver: local
  microservice_account_db_testing:
    driver: local
